spring:
  application:
    name=MeowMarket
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    username: meowmarketapp@gmail.com
    password: qmnz irmq nzfh nccj
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    csrf:
      enabled: true




